### ISSUE TITLE
css selector parser cannot advance past unsupported pseudo classes

### ISSUE THREAD

**Issue by jamespsteinberg** [leeoniya/dropcss#57] opened 2021-11-17 08:01 UTC
Was just testing this with the CSS on apple.com for fun. The library will freeze and crash if given this css:

```
.anything-dash-body{
  font-weight:400;
}
.anything-dash-body:lang(ar){
  line-height: 1;
}
```

 The library mistakenly thinks .anything-dash-body is a body tag and does not remove it which is "ok", but I don't think it should freeze and crash when failing. All other selectors, etc seem to be ok.

**Comment by jamespsteinberg** [comment] 2021-11-17 08:18
I am still going through the library for how you get this so fast so maybe the "-body" names can't be handled. But I can parse all html tags pretty reliably by adding a space in front of every new line and checking for all unique selector signs before and after: [https://www.w3schools.com/cssref/css_selectors.asp](https://www.w3schools.com/cssref/css_selectors.asp)

i.e.
```
var lineText = ".anything-dash-body:lang(ar){"
lineText = " " + lineText;
var regex = new RegExp("(?<= |{|\\[|:|,|\\.|>|\\+|~|=|~=|\\||=|^=|$=|\\*=|\\*)" + escapeRegExp("body") + "(?= |{|\\[|:|,|\\.|>|\\+|~|=|~=|\\||=|^=|$=|\\*=|\\*)", "g");
var matches = lineText.match(regex);
```

**Comment by leeoniya** [comment] 2021-11-17 08:22
will take a look tomorrow

**Comment by leeoniya** [comment] 2021-11-17 21:50
i pushed an infinite loop guard in the selector parser so we can actually debug this :rofl: 

the problem is not with `body`, but with the `:lang(ar)` pseudo-selector; dropcss should strip or ignore these since there's no way to assert them from the markup.

```js
<!doctype html>
<html>
  <head>
    <title>loopy</title>
    <script src="./dist/dropcss.iife.js"></script>
  </head>
  <body>
    <script>
      dropcss({
        html: '<div class="anything-dash-body"></div>',
        css: `
          .anything-dash-body:lang(ar){
            line-height: 1;
          }
        `,
      });
    </script>
  </body>
</html>
```

**Comment by jamespsteinberg** [comment] 2021-11-17 22:08
I didn’t explain well. It seems to only hang on the combination of thinking it’s an html tag and the lang selector. It seems to work fine if either are present alone.

**Comment by jamespsteinberg** [comment] 2021-11-17 22:10
But that works awesome, I’ll test out a few more pages tomorrow. I suppose the class name part is a very minor separate issue

**Comment by leeoniya** [comment] 2021-11-17 22:47
fixed by attached commit.

**Closed** 2021-11-17 22:47 UTC
Labels: bug

**Comment by leeoniya** [comment] 2021-11-17 23:07
> It seems to only hang on the combination of thinking it’s an html tag and the lang selector. It seems to work fine if either are present alone.

that's because the secondary, more-expensive selector parser only runs when there is matched html tags for the pre-parsing pass that pulls out only ids, classes and tag names. so it will first try to find `.anything-dash-body`, and only then will try parsing the full selector with the `:lang(ar)` pseudo, which is where it crashed.
